#!/bin/bash

# This script is designed to allow the user to select an mp4 file via dmenu and then play it with mpv amd enable fullscreen
# Be sure that both dmenu and mpv are installed

    du -a ~/Path_to_mp4_files | cut -f2- | grep mp4$ | dmenu -p prompt -l 60 | xargs -I {} mpv "{}" --fs
