#!/bin/bash
   
# This script is designed to allow the user to create a random list of 3 choices via dmenu and then play it with mpv
# In this case this command shuffles The Office but can be replaced by a name or file type
  
du -a ~/Path_of_Media | cut -f2- | grep "The Office" |shuf | dmenu -p prompt -l 3 | xargs -I {} mpv "{}" --fs
